import type { MonthlyPayPromotionList } from "~apps/components/charts/PayPromotionChart";

export const payPromotionMocks: MonthlyPayPromotionList[] = [
  {
    activated: true,
    postingBeginAt: new Date("2025-08-02"),
    postingEndAt: new Date("2025-08-10"),
    promotionId: 0,
    title: "Card Promotion: June Blast",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-08-15"),
    postingEndAt: new Date("2025-08-26"),
    promotionId: 1,
    title: "Summer Payment Cashback_1",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-08-20"),
    postingEndAt: new Date("2025-08-25"),
    promotionId: 2,
    title: "Summer Payment Cashback_2",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-08-05"),
    postingEndAt: new Date("2025-08-15"),
    promotionId: 3,
    title: "Summer Payment Cashback_3",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-05-15"),
    postingEndAt: new Date("2025-08-27"),
    promotionId: 4,
    title: "Summer Payment Cashback_2",
  },
  {
    activated: false,
    postingBeginAt: new Date("2025-05-10"),
    postingEndAt: new Date("2025-05-30"),
    promotionId: 5,
    title: "Spring Early Bird Discount",
  },
  {
    activated: false,
    postingBeginAt: new Date("2025-04-20"),
    postingEndAt: new Date("2025-08-05"),
    promotionId: 6,
    title: "Cardholder Loyalty Offer",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-08-01"),
    postingEndAt: new Date("2025-08-10"),
    promotionId: 7,
    title: "Mid-Year Bonus Program",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-08-05"),
    postingEndAt: new Date("2025-08-20"),
    promotionId: 8,
    title: "Back-to-School Rewards",
  },
  {
    activated: false,
    postingBeginAt: new Date("2025-08-01"),
    postingEndAt: null,
    promotionId: 9,
    title: "Spending Bonus",
  },
  {
    activated: true,
    postingBeginAt: new Date("2025-8-10"),
    postingEndAt: new Date("2025-8-30"),
    promotionId: 10,
    title: "Special Offer",
  },
];
